### ISSUE TITLE
Enhance as a more privacy friendly visual event builder extension rather than deprecated autotracking

### ISSUE THREAD

**Issue by adrianlyjak** [rudderlabs/rudder-sdk-js-autotrack#1]
If the concept of autotracking is not something that you are interested in pursuing further, than I understand deprecating it. However, a lot of competitors in the space do support some sort of autotracking with event builders, so it seems relevant to not entirely ditch the concept. Seems like there's value to be able to quickly build out events based off of selectors without actually updating the website code, and that concept is separate from the privacy (and network) unfriendly act of just shipping every event to the analytics server. 

Competitor examples:
- [Segment Visual Tagger](https://segment.com/docs/connections/sources/visual-tagger/) 
- [Freshpaint Visual Editor](https://freshpaint.gitbook.io/docs/data-management/visual-editor)

Architecture:

If the backend were given some sort of functionality to store event match configurations, the dynamic configuration could be loaded as an API call. Then, this plugin would check for match criteria on events rather than tracking everything. This would probably want some sort of visual editor like the competitors have. 

Also, I understand wanting to separate this feature from the main js sdk, but it seems like it could easily be turned into more of a plugin rather than a full fork. It would just be reliant on the main `rudder-sdk-js` library. The `utils/autotrack.js` file is fairly standalone, it just needs a mechanism to be registered at an appropriate time (which `analytics.js` is currently handling).

![visual tracking](https://user-images.githubusercontent.com/2024018/102920362-aae6df00-4458-11eb-89f7-6973b55efdfe.png)

This is kind of a parallel feature, but other analytics providers like heap take this a step further, and autotrack+provide a visual tagger that can retroactively tag events, so still seems like a somewhat relevant place to discuss.

**Comment by saikumarrs** [comment]
Hi @adrianlyjak, thanks for the suggestions. We are on the path to restructure the SDK to be more of a plugin based in the near future. We'll definitely keep this mind.
However, autotrack may not be prioritized anytime soon.
